from app.bot.shared.keyboards.keyboards import InlineKbs, ReplyKbs

main_keyboard = ReplyKbs.new_user_vk()
played_before_keyboard = ReplyKbs.played_before_vk()
registration_optional_details_keyboard = InlineKbs.registration_optional_details_vk
registration_platform_keyboard = InlineKbs.registration_platform_vk
registration_review_keyboard = InlineKbs.registration_review_vk
registration_link_review_keyboard = InlineKbs.registration_link_review_vk
link_candidates_keyboard = InlineKbs.link_candidates_vk
make_admin_candidates_keyboard = InlineKbs.make_admin_candidates_vk
poker_params_keyboard = InlineKbs.poker_params_vk
poker_add_player_candidates_keyboard = InlineKbs.poker_add_player_candidates_vk
poker_cashier_candidates_keyboard = InlineKbs.poker_cashier_candidates_vk
poker_remove_player_candidates_keyboard = InlineKbs.poker_remove_player_candidates_vk
poker_buyin_candidates_keyboard = InlineKbs.poker_buyin_candidates_vk
registration_candidates_keyboard = InlineKbs.registration_candidates_vk
