from enum import Enum


class UserText(Enum):
  BOT_INFO = (
    "Привет👋, я покер-бот🤖.\n\n"
    "Я помогаю проводить покерные игры: считаю закупы🏦 и переводы💲 победителям💍 от проигравших❌.\n\n"
    "Я веду статистику игр с 2023 года, а также умею принимать ставки на результаты покерных игр.\n\n"
    "Чтобы начать пользоваться моими функциями, тебе нужно зарегистрироваться."
  )

  REGISTRATION_PLAYED_BEFORE_Q = "Ты раньше играл с нами?"
  REGISTRATION_PLAYED_BEFORE_Y = "Найди себя в списке. Если тебя нет - жми Меня нет в списке."
  REGISTRATION_PLAYED_BEFORE_EMPTY = "Не найдено ранее игравших пользователей - введи свое имя"
  REGISTRATION_NEW_NAME_PROMPT = "Введи свои имя и фамилию русскими буквами через пробел. Пожалуйста, вводи настоящие!"
  REGISTRATION_EXIST = "Ты уже зарегистрирован."
  REGISTRATION_WAIT = "Заявка отправлена. После её рассмотрения тебе придёт сообщение."
  REGISTRATION_APPROVED = "Ты успешно зарегистрирован!"
  REGISTRATION_NOT_APPROVED = "Ты не зарегистрирован! Спроси у админа почему."
  REGISTRATION_PENDING = "Твоя заявка уже ожидает подтверждения администратора."
  REGISTRATION_IN_PROGRESS = "Мы уже начали регистрацию. Продолжай по предыдущему сообщению."
  REGISTRATION_EMPTY_NAME = "Имя не должно быть пустым."
  REGISTRATION_CHOOSE_FROM_LIST = "Не нашел такую запись в списке. Выбери игрока из списка."
  REGISTRATION_READ_ERROR = "Не удалось прочитать данные. Попробуй ещё раз."
  REGISTRATION_ID_ERROR = "Не удалось определить Telegram ID."
  REGISTRATION_OPTIONAL_DETAILS_PROMPT = "Если хочешь, укажи свои банк и номер телефона. В случае твоей победы по этим данным тебе быстрее переведут деньги."
  REGISTRATION_PLATFORM_PROMPT = "Выбери платформу для уведомлений:"
  REGISTRATION_BANK_PROMPT = "Введи название банка:"
  REGISTRATION_PHONE_PROMPT = "Введи номер телефона, начиная с 7:"
  REGISTRATION_PHONE_INVALID = "Номер должен начинаться с 7 и содержать 11 цифр."

  START_POKER = "Начало покера. Желающим принять участие в игре пора заходить в покер рум!"
  START_BETTING = "Ставки открыты. Можно делать ставки на текущую игру."
  FINISH_POKER = "Покер завершен.\n\nИтог:\n🏦 Закупы: {buyins}\n💸 Кешаут: {cashout_rub} ₽"
  STATUS_NEED_REGISTRATION = "Сначала зарегистрируйся."
  STATUS_PENDING = "Твоя заявка еще на рассмотрении у администратора."
  STATUS_ROOM_CLOSED = "Сейчас покер рум закрыт."
  STATUS_ROOM_NOT_ADDED = "Ты не добавлен в покер рум! Спроси у админа почему."
  STATUS_BUYINS = "🏦 Закупы: {buyins}"
  ROOM_JOINED = "Добро пожаловать в покер рум!"
  ROOM_ALREADY_JOINED = "Ты уже добавлен в покер рум."
  BETTING_MENU = "Раздел ставок."
  BETTING_NOT_OPEN = "Сейчас ставки закрыты."
  BETTING_TOURNAMENT_CHOOSE = "Выбери турнир для ставки:"
  BETTING_SIZE_CHOOSE = "Выбери размер ставки:"
  BETTING_WINNER_CHOOSE = "Выбери предполагаемого победителя:"
  BETTING_LOSER_CHOOSE = "Выбери предполагаемого проигравшего:"
  BETTING_CONFIRM = "Проверь ставку:\n{tournament}\nСумма: {amount_rub} ₽\nПобедитель: {winner}\nПроигравший: {loser}"
  BETTING_AMOUNT_PROMPT = "Введи сумму ставки в рублях (целым числом)."
  BETTING_AMOUNT_INVALID = "Сумма должна быть положительным целым числом."
  BETTING_ALREADY_EXISTS = "Ставка на этот турнир уже сделана."
  BETTING_CREATED = "Ставка принята: {tournament} — {amount_rub} ₽."
  BETTING_CURRENT_EMPTY = "Активных турниров для ставок сейчас нет."
  BETTING_CURRENT_LIST = "Сейчас открыты турниры:\n{tournaments}"
  BETTING_USER_BETS_EMPTY = "У тебя пока нет ставок в текущей игре."
  BETTING_USER_BETS = "Твои текущие ставки:\n{bets}"
  BETTING_STAT_INDICATORS = "Показатели статистики ставок:"
  BETTING_STAT_MODE = "Выбери режим статистики ставок:"
  BETTING_STAT_SELECTED = "Выбран показатель: {indicator}"
  BETTING_STAT_REPORT = "Статистика ставок:\n\n{report}"
  POKER_MENU = "Раздел покера."
  POKER_INFO = "Информация о покере."
  POKER_STAT_INDICATORS = "Показатели статистики покера:"
  POKER_STAT_REPORT = "Статистика покера:\n\n{report}"
