"""Smoke checks for preserved handler registration order and public webhook imports."""

from app.bot.telegram.handlers.handlers_admin import router as admin_router
from app.bot.telegram.handlers.handlers_user import router as user_router
from app.bot.vk.handlers_admin import handle_admin_text_commands, handle_message_event
from app.bot.vk.handlers_user import handle_user_message_event, handle_user_message_new

EXPECTED_ADMIN = [
    "start_poker_menu",
    "start_poker_with_param",
    "finish_poker",
    "calculate_poker",
    "calculate_poker_inline",
    "start_betting",
    "start_betting_inline",
    "create_poll_menu",
    "create_poll_choose_other",
    "create_poll_cancel",
    "create_poll_set_month",
    "set_cashier_menu",
    "open_correct_poker_menu",
    "back_from_correct_poker_menu",
    "set_cashier_callback",
    "set_cashier_from_room_callback",
    "poker_room_manage_callback",
    "poker_room_approve_callback",
    "poker_room_reject_callback",
    "add_player_menu",
    "add_player_callback",
    "add_player_new_callback",
    "add_player_cancel_callback",
    "add_new_player_name_input",
    "remove_player_menu",
    "remove_player_callback",
    "unban_player_menu",
    "unban_player_callback",
    "buyin_menu",
    "buyin_select_callback",
    "buyin_correct_select_callback",
    "buyin_correct_amount_input",
    "buyin_correct_confirm_callback",
    "buyin_count_callback",
    "buyin_cancel_callback",
    "cashout_select_callback",
    "cashout_amount_input",
    "make_admin_menu",
    "make_admin_select_callback",
    "back_to_room_admin_panel",
    "approve_registration_callback",
    "bet_receipt_manual_callback",
    "correct_registration_callback",
    "finish_correct_user",
    "reject_registration_callback",
    "link_registration_callback",
    "choose_link_target_callback",
    "choose_link_target_page_callback",
]

EXPECTED_USER = [
    "start_command",
    "start_registration",
    "show_bot_info",
    "show_user_status",
    "join_poker_room",
    "open_room_admin_panel",
    "start_room_poll",
    "show_poll_results",
    "poll_noop",
    "poll_page_nav",
    "poll_day_toggle",
    "poll_suggest_day",
    "poll_suggest_day_input",
    "poll_done",
    "poll_cancel",
    "open_betting_menu",
    "open_poker_menu",
    "open_info_menu",
    "open_next_poker_date_menu",
    "open_admin_panel",
    "back_from_admin_to_main",
    "back_to_main_from_betting",
    "back_to_main_from_poker",
    "back_to_main_from_room",
    "back_to_main_from_poll_menu",
    "show_poker_info",
    "show_betting_info",
    "back_to_main_from_info",
    "show_betting_rules",
    "show_betting_stat_info",
    "show_betting_achievement_info",
    "show_poker_stat_info",
    "show_poker_achievement_info",
    "show_poker_history_years",
    "poker_history_cancel",
    "poker_history_year_pick",
    "poker_history_page",
    "poker_history_date_pick",
    "show_poker_stat_indicators",
    "poker_stat_year_page",
    "poker_stat_year_toggle",
    "poker_stat_year_cancel",
    "poker_stat_year_done",
    "poker_stat_page",
    "poker_stat_indicator_selected",
    "poker_stat_done",
    "poker_stat_cancel",
    "poker_stat_sort_page",
    "poker_stat_sort_toggle",
    "poker_stat_sort_cancel",
    "poker_stat_sort_done",
    "show_current_betting_tournaments",
    "show_regular_betting_tournament_stat",
    "show_year_betting_tournament_stat",
    "back_to_betting_from_current_tournaments",
    "show_betting_stat_indicators",
    "betting_stat_year_page",
    "betting_stat_year_toggle",
    "betting_stat_year_cancel",
    "betting_stat_year_done",
    "betting_stat_mode_selected",
    "betting_stat_page",
    "betting_stat_indicator_selected",
    "betting_stat_done",
    "betting_stat_cancel",
    "betting_stat_sort_page",
    "betting_stat_sort_toggle",
    "betting_stat_sort_cancel",
    "betting_stat_sort_done",
    "start_pay_bet",
    "start_make_bet",
    "choose_registration_branch",
    "repeat_registration_branch_prompt",
    "finish_existing_row_id_registration",
    "registration_existing_page",
    "choose_registration_platform",
    "finish_registration",
    "choose_optional_registration_data",
    "choose_bet_tournament",
    "choose_bet_size",
    "choose_bet_winner",
    "choose_bet_loser",
    "confirm_bet",
    "repeat_bet_inline_flow",
    "process_bet_payment_receipt",
    "process_chips_input",
    "save_optional_bank_name",
    "save_optional_phone",
    "repeat_optional_registration_prompt",
]


def test_telegram_handler_order():
    assert [
        handler.callback.__name__
        for handler in admin_router.message.handlers + admin_router.callback_query.handlers
    ] != []
    for router, expected in ((admin_router, EXPECTED_ADMIN), (user_router, EXPECTED_USER)):
        registered = [
            handler.callback.__name__
            for handler in router.message.handlers + router.callback_query.handlers
        ]
        assert sorted(registered) == sorted(expected)
        assert len(registered) == len(expected)


def test_vk_webhook_exports():
    assert all(
        callable(handler)
        for handler in (
            handle_admin_text_commands,
            handle_message_event,
            handle_user_message_event,
            handle_user_message_new,
        )
    )


EXPECTED_ADMIN_MESSAGE = [
    "start_poker_menu",
    "finish_poker",
    "calculate_poker",
    "start_betting",
    "create_poll_menu",
    "set_cashier_menu",
    "open_correct_poker_menu",
    "back_from_correct_poker_menu",
    "add_player_menu",
    "add_new_player_name_input",
    "remove_player_menu",
    "unban_player_menu",
    "buyin_menu",
    "buyin_correct_amount_input",
    "cashout_amount_input",
    "make_admin_menu",
    "back_to_room_admin_panel",
    "finish_correct_user",
]
EXPECTED_ADMIN_CALLBACK_QUERY = [
    "start_poker_with_param",
    "calculate_poker_inline",
    "start_betting_inline",
    "create_poll_choose_other",
    "create_poll_cancel",
    "create_poll_set_month",
    "set_cashier_callback",
    "set_cashier_from_room_callback",
    "poker_room_manage_callback",
    "poker_room_approve_callback",
    "poker_room_reject_callback",
    "add_player_callback",
    "add_player_new_callback",
    "add_player_cancel_callback",
    "remove_player_callback",
    "unban_player_callback",
    "buyin_select_callback",
    "buyin_correct_select_callback",
    "buyin_correct_confirm_callback",
    "buyin_count_callback",
    "buyin_cancel_callback",
    "cashout_select_callback",
    "make_admin_select_callback",
    "approve_registration_callback",
    "bet_receipt_manual_callback",
    "correct_registration_callback",
    "reject_registration_callback",
    "link_registration_callback",
    "choose_link_target_callback",
    "choose_link_target_page_callback",
]
EXPECTED_USER_MESSAGE = [
    "start_command",
    "start_registration",
    "show_bot_info",
    "show_user_status",
    "join_poker_room",
    "open_room_admin_panel",
    "start_room_poll",
    "show_poll_results",
    "poll_suggest_day_input",
    "open_betting_menu",
    "open_poker_menu",
    "open_info_menu",
    "open_next_poker_date_menu",
    "open_admin_panel",
    "back_from_admin_to_main",
    "back_to_main_from_betting",
    "back_to_main_from_poker",
    "back_to_main_from_room",
    "back_to_main_from_poll_menu",
    "show_poker_info",
    "show_betting_info",
    "back_to_main_from_info",
    "show_betting_rules",
    "show_betting_stat_info",
    "show_betting_achievement_info",
    "show_poker_stat_info",
    "show_poker_achievement_info",
    "show_poker_history_years",
    "show_poker_stat_indicators",
    "show_current_betting_tournaments",
    "show_regular_betting_tournament_stat",
    "show_year_betting_tournament_stat",
    "back_to_betting_from_current_tournaments",
    "show_betting_stat_indicators",
    "start_pay_bet",
    "start_make_bet",
    "repeat_registration_branch_prompt",
    "finish_registration",
    "repeat_bet_inline_flow",
    "process_bet_payment_receipt",
    "process_chips_input",
    "save_optional_bank_name",
    "save_optional_phone",
    "repeat_optional_registration_prompt",
]
EXPECTED_USER_CALLBACK_QUERY = [
    "poll_noop",
    "poll_page_nav",
    "poll_day_toggle",
    "poll_suggest_day",
    "poll_done",
    "poll_cancel",
    "poker_history_cancel",
    "poker_history_year_pick",
    "poker_history_page",
    "poker_history_date_pick",
    "poker_stat_year_page",
    "poker_stat_year_toggle",
    "poker_stat_year_cancel",
    "poker_stat_year_done",
    "poker_stat_page",
    "poker_stat_indicator_selected",
    "poker_stat_done",
    "poker_stat_cancel",
    "poker_stat_sort_page",
    "poker_stat_sort_toggle",
    "poker_stat_sort_cancel",
    "poker_stat_sort_done",
    "betting_stat_year_page",
    "betting_stat_year_toggle",
    "betting_stat_year_cancel",
    "betting_stat_year_done",
    "betting_stat_mode_selected",
    "betting_stat_page",
    "betting_stat_indicator_selected",
    "betting_stat_done",
    "betting_stat_cancel",
    "betting_stat_sort_page",
    "betting_stat_sort_toggle",
    "betting_stat_sort_cancel",
    "betting_stat_sort_done",
    "choose_registration_branch",
    "finish_existing_row_id_registration",
    "registration_existing_page",
    "choose_registration_platform",
    "choose_optional_registration_data",
    "choose_bet_tournament",
    "choose_bet_size",
    "choose_bet_winner",
    "choose_bet_loser",
    "confirm_bet",
]


def test_telegram_observer_order():
    for router, kind in ((admin_router, "ADMIN"), (user_router, "USER")):
        for observer_name in ("message", "callback_query"):
            observer = getattr(router, observer_name)
            expected = globals()[f"EXPECTED_{kind}_{observer_name.upper()}"]
            assert [handler.callback.__name__ for handler in observer.handlers] == expected
