from app.bot.shared.kbs import InlineKbs, ReplyKbs

main_keyboard = ReplyKbs.new_user_tg()
played_before_keyboard = InlineKbs.played_before_tg
registration_optional_details_keyboard = InlineKbs.registration_optional_details_tg
registration_platform_keyboard = InlineKbs.registration_platform_tg
registration_review_keyboard = InlineKbs.registration_review_tg
registration_link_review_keyboard = InlineKbs.registration_link_review_tg
link_candidates_keyboard = InlineKbs.link_candidates_tg
registration_candidates_keyboard = InlineKbs.registration_candidates_tg
