from enum import Enum

from app.bot.shared.texts.inline.shared import buttons_reply as InlineText


class NewUserBtns(Enum):
  ABOUT = InlineText.NEWUSERBTNS_TEXT_01
  REGISTRATION = InlineText.NEWUSERBTNS_TEXT_02

class MainBtns(Enum):
  NEXT_POKER_DATE = InlineText.MAINBTNS_TEXT_01
  ROOM = InlineText.MAINBTNS_TEXT_02
  POKER = InlineText.MAINBTNS_TEXT_03
  BETTING = InlineText.MAINBTNS_TEXT_04
  INFO = InlineText.MAINBTNS_TEXT_05
  ADMIN = InlineText.MAINBTNS_TEXT_06


class PollMenuBtns(Enum):
  VOTE = InlineText.POLLMENUBTNS_TEXT_01
  RESULTS = InlineText.POLLMENUBTNS_TEXT_02
  TO_MAIN = InlineText.POLLMENUBTNS_TEXT_03


class MainInfoBtns(Enum):
  POKER_INFO = InlineText.MAININFOBTNS_TEXT_01
  BETTING_INFO = InlineText.MAININFOBTNS_TEXT_02
  TO_MAIN = InlineText.MAININFOBTNS_TEXT_03

class AdminMainBtns(Enum):
  START_POKER = InlineText.ADMINMAINBTNS_TEXT_01
  CREATE_POLL = InlineText.ADMINMAINBTNS_TEXT_02
  MAKE_ADMIN = InlineText.ADMINMAINBTNS_TEXT_03
  TO_MAIN = InlineText.ADMINMAINBTNS_TEXT_04
  BETTING = InlineText.ADMINMAINBTNS_TEXT_05

class AdminBettingBtns(Enum):
  OPEN = InlineText.ADMINBETTINGBTNS_TEXT_01
  CLOSE = InlineText.ADMINBETTINGBTNS_TEXT_02
  BACK = InlineText.ADMINBETTINGBTNS_TEXT_03

class RoomBtns(Enum):
  STATUS = InlineText.ROOMBTNS_TEXT_01
  BUYIN = InlineText.ROOMBTNS_TEXT_02
  TO_MAIN = InlineText.ROOMBTNS_TEXT_03
  POKER_ADMIN = InlineText.ROOMBTNS_TEXT_04

class AdminRoomBtns(Enum):
  SET_CASHIER = InlineText.ADMINROOMBTNS_TEXT_01
  START_BETTING = InlineText.ADMINROOMBTNS_TEXT_02
  FINISH_POKER = InlineText.ADMINROOMBTNS_TEXT_03
  CALCULATE_POKER = InlineText.ADMINROOMBTNS_TEXT_04
  ADD_PLAYER = InlineText.ADMINROOMBTNS_TEXT_05
  REMOVE_PLAYER = InlineText.ADMINROOMBTNS_TEXT_06
  UNBAN_PLAYER = InlineText.ADMINROOMBTNS_TEXT_07
  CORRECT_POKER = InlineText.ADMINROOMBTNS_TEXT_08
  TO_ROOM = InlineText.ADMINROOMBTNS_TEXT_09


class AdminRoomCorrectBtns(Enum):
  SET_CASHIER = InlineText.ADMINROOMCORRECTBTNS_TEXT_01
  ADD_PLAYER = InlineText.ADMINROOMCORRECTBTNS_TEXT_02
  REMOVE_PLAYER = InlineText.ADMINROOMCORRECTBTNS_TEXT_03
  BUYIN_CORRECT = InlineText.ADMINROOMCORRECTBTNS_TEXT_04
  TO_ADMIN_ROOM = InlineText.ADMINROOMCORRECTBTNS_TEXT_05

class BettingBtns(Enum):
  MAKE_BET = InlineText.BETTINGBTNS_TEXT_01
  PAY_BET = InlineText.BETTINGBTNS_TEXT_02
  CURRENT_TOURS = InlineText.BETTINGBTNS_TEXT_03
  BETTING_STAT = InlineText.BETTINGBTNS_TEXT_04
  TO_MAIN = InlineText.BETTINGBTNS_TEXT_05

class BettingInfoBtns(Enum):
  BETTING_RULES = InlineText.BETTINGINFOBTNS_TEXT_01
  BETTING_ACH_INFO = InlineText.BETTINGINFOBTNS_TEXT_02
  BETTING_STAT_INFO = InlineText.BETTINGINFOBTNS_TEXT_03
  TO_MAIN = InlineText.BETTINGINFOBTNS_TEXT_04

class BettingCurrentBtns(Enum):
  REG_TOURNAMENT = InlineText.BETTINGCURRENTBTNS_TEXT_01
  YEAR_TOURNAMENT = InlineText.BETTINGCURRENTBTNS_TEXT_02
  TO_MAIN = InlineText.BETTINGCURRENTBTNS_TEXT_03

class PokerBtns(Enum):
  POKER_STAT = InlineText.POKERBTNS_TEXT_01
  HISTORY = InlineText.POKERBTNS_TEXT_02
  POLL = InlineText.POKERBTNS_TEXT_03
  TO_MAIN = InlineText.POKERBTNS_TEXT_04

class PokerInfoBtns(Enum):
  POKER_ACH_INFO = InlineText.POKERINFOBTNS_TEXT_01
  POKER_STAT_INFO = InlineText.POKERINFOBTNS_TEXT_02
  HISTORY = InlineText.POKERINFOBTNS_TEXT_03
  TO_MAIN = InlineText.POKERINFOBTNS_TEXT_04
