from enum import Enum


class AdminText(Enum):
  NEW_REGISTRATION = "Новая заявка на регистрацию"
  NO_RIGHTS = "Недостаточно прав."
  USER_NOT_FOUND = "Пользователь не найден."
  MAKE_ADMIN_USAGE = "Использование: /make_admin <row_id>"
  MAKE_ADMIN_SUCCESS = "Права администратора выданы."
  LINK_PROMPT = "Отправь row_id существующего пользователя, к которому нужно привязать эту заявку."
  LINK_USAGE = "Нужно отправить только числовой row_id существующего пользователя."
  LINK_CHOICES_EMPTY = "Нет одобренных пользователей для привязки."
  LINK_CHOICES_TITLE = "Одобренные пользователи:"
  LINK_SUCCESS = "Заявка привязана к существующему пользователю."
  LINK_ACTION = "Привязка начата."
  LINK_CONFLICT = "У существующего пользователя уже есть такой platform id."
  LINK_COMMAND_USAGE = "Использование: link <pending_row_id> <existing_row_id>"
  APPROVE_COMMAND_USAGE = "Использование: approve <row_id>"
  REJECT_COMMAND_USAGE = "Использование: reject <row_id>"
  APPROVE_ACTION = "Заявка одобрена."
  REJECT_ACTION = "Заявка отклонена."
  IDENTIFY_USER_ERROR = "Не удалось определить пользователя."
  REQUEST_NOT_FOUND = "Заявка не найдена."
  REQUEST_ALREADY_APPROVED = "Одобренную заявку нельзя отклонить."
  BUTTON_APPROVE = "Одобрить"
  BUTTON_REJECT = "Отклонить"
  BUTTON_LINK = "Привязать"
